// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asqgjajkhnpulmzvwfun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzcWdqYWpraG5wdWxtenZ3ZnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzA4MzEsImV4cCI6MjA3MDI0NjgzMX0.vYGElrDn1jwwk5aKmfu367bvlSybOhOL5hIB2xlOV1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});